// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include <Arduino.h>

void ResetScoreBrickFunction(lv_event_t * e)
{
	//Serial.println("ResetScoreBrickFunction triggered");
	;
	vTaskDelay(50);
}

void ResetScoreWolfFunction(lv_event_t * e)
{
	//Serial.println("ResetScoreWolfFunction triggered");
	;
	vTaskDelay(50);
}
