// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"


// COMPONENT StatusPanel

lv_obj_t *ui_StatusPanel_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_StatusPanel;
cui_StatusPanel = lv_obj_create(comp_parent);
lv_obj_set_width( cui_StatusPanel, 480);
lv_obj_set_height( cui_StatusPanel, 32);
lv_obj_set_x( cui_StatusPanel, 0 );
lv_obj_set_y( cui_StatusPanel, -145 );
lv_obj_set_align( cui_StatusPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_StatusPanel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_color(cui_StatusPanel, lv_color_hex(0xCAC8C8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_StatusPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(cui_StatusPanel, lv_color_hex(0xCAC8C8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(cui_StatusPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_Bar1;
cui_Bar1 = lv_bar_create(cui_StatusPanel);
lv_bar_set_value(cui_Bar1,100,LV_ANIM_OFF);
lv_obj_set_width( cui_Bar1, 150);
lv_obj_set_height( cui_Bar1, 10);
lv_obj_set_x( cui_Bar1, -120 );
lv_obj_set_y( cui_Bar1, -1 );
lv_obj_set_align( cui_Bar1, LV_ALIGN_CENTER );
lv_obj_set_style_radius(cui_Bar1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_Bar1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_Bar1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(cui_Bar1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(cui_Bar1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(cui_Bar1, 25, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(cui_Bar1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(cui_Bar1, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_Bar1, lv_color_hex(0xBB0000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_Bar1, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(cui_Bar1, lv_color_hex(0xBB0000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(cui_Bar1, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(cui_Bar1, 25, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(cui_Bar1, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_t *cui_Score;
cui_Score = lv_label_create(cui_StatusPanel);
lv_obj_set_width( cui_Score, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_Score, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_Score, 170 );
lv_obj_set_y( cui_Score, -11 );
lv_obj_set_align( cui_Score, LV_ALIGN_TOP_MID );
lv_label_set_text(cui_Score,"Score: 00000");

lv_obj_t *cui_BestScore;
cui_BestScore = lv_label_create(cui_StatusPanel);
lv_obj_set_width( cui_BestScore, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_BestScore, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_BestScore, 40 );
lv_obj_set_y( cui_BestScore, -11 );
lv_obj_set_align( cui_BestScore, LV_ALIGN_TOP_MID );
lv_label_set_text(cui_BestScore,"Best: 00000");

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_STATUSPANEL_NUM);
children[UI_COMP_STATUSPANEL_STATUSPANEL] = cui_StatusPanel;
children[UI_COMP_STATUSPANEL_BAR1] = cui_Bar1;
children[UI_COMP_STATUSPANEL_SCORE] = cui_Score;
children[UI_COMP_STATUSPANEL_BESTSCORE] = cui_BestScore;
lv_obj_add_event_cb(cui_StatusPanel, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_StatusPanel, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_StatusPanel_create_hook(cui_StatusPanel);
return cui_StatusPanel; 
}

