// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_COMP_STATUSPANEL_H
#define _UI_COMP_STATUSPANEL_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT StatusPanel
#define UI_COMP_STATUSPANEL_STATUSPANEL 0
#define UI_COMP_STATUSPANEL_BAR1 1
#define UI_COMP_STATUSPANEL_SCORE 2
#define UI_COMP_STATUSPANEL_BESTSCORE 3
#define _UI_COMP_STATUSPANEL_NUM 4
lv_obj_t *ui_StatusPanel_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
