// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Spinner1 = lv_spinner_create(ui_Screen1,1000,90);
lv_obj_set_width( ui_Spinner1, 80);
lv_obj_set_height( ui_Spinner1, 80);
lv_obj_set_x( ui_Spinner1, -7 );
lv_obj_set_y( ui_Spinner1, -30 );
lv_obj_set_align( ui_Spinner1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Spinner1, LV_OBJ_FLAG_CLICKABLE );    /// Flags

ui_TextArea1 = lv_textarea_create(ui_Screen1);
lv_obj_set_width( ui_TextArea1, 300);
lv_obj_set_height( ui_TextArea1, 40);
lv_obj_set_x( ui_TextArea1, 0 );
lv_obj_set_y( ui_TextArea1, -110 );
lv_obj_set_align( ui_TextArea1, LV_ALIGN_CENTER );
lv_textarea_set_text(ui_TextArea1,"Waiting for Bluetooth Connection");
lv_textarea_set_placeholder_text(ui_TextArea1,"Placeholder...");



ui_TextArea2 = lv_textarea_create(ui_Screen1);
lv_obj_set_width( ui_TextArea2, 300);
lv_obj_set_height( ui_TextArea2, 102);
lv_obj_set_x( ui_TextArea2, 0 );
lv_obj_set_y( ui_TextArea2, 85 );
lv_obj_set_align( ui_TextArea2, LV_ALIGN_CENTER );
lv_textarea_set_text(ui_TextArea2,"Some Information from ESP32");
lv_textarea_set_placeholder_text(ui_TextArea2,"Placeholder...");



lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}
