// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Settings_screen_init(void)
{
ui_Settings = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Settings, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Settings, lv_color_hex(0x4C4E5B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Settings, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Settings, lv_color_hex(0x393B46), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_Settings, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_Settings, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_Settings, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Settings, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Settings, lv_color_hex(0x191B20), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Settings, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_Settings, 140, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_Settings, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_Settings, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_Settings, 4, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SettingsLable = lv_label_create(ui_Settings);
lv_obj_set_width( ui_SettingsLable, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SettingsLable, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SettingsLable, 0 );
lv_obj_set_y( ui_SettingsLable, 10 );
lv_obj_set_align( ui_SettingsLable, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_SettingsLable,"Settings");
lv_obj_set_style_text_font(ui_SettingsLable, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_VolumePanel = lv_obj_create(ui_Settings);
lv_obj_set_width( ui_VolumePanel, 130);
lv_obj_set_height( ui_VolumePanel, 260);
lv_obj_set_x( ui_VolumePanel, 20 );
lv_obj_set_y( ui_VolumePanel, 40 );
lv_obj_clear_flag( ui_VolumePanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_VolumePanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_VolumePanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelVolMax1 = lv_label_create(ui_VolumePanel);
lv_obj_set_width( ui_LabelVolMax1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelVolMax1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelVolMax1, 0 );
lv_obj_set_y( ui_LabelVolMax1, 200 );
lv_label_set_text(ui_LabelVolMax1,"Min");

ui_LabelVolMax = lv_label_create(ui_VolumePanel);
lv_obj_set_width( ui_LabelVolMax, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelVolMax, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelVolMax, 0 );
lv_obj_set_y( ui_LabelVolMax, 20 );
lv_label_set_text(ui_LabelVolMax,"Max");

ui_VolumeSlider = lv_slider_create(ui_VolumePanel);
lv_obj_set_width( ui_VolumeSlider, 65);
lv_obj_set_height( ui_VolumeSlider, 150);
lv_obj_set_align( ui_VolumeSlider, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_VolumeSlider, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_VolumeSlider, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_VolumeSlider, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_VolumeSlider, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_VolumeSlider, &ui_img_pot_ver_line_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_pad_left(ui_VolumeSlider, 28, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_VolumeSlider, 28, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_VolumeSlider, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_VolumeSlider, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_VolumeSlider, lv_color_hex(0x00FF08), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_VolumeSlider, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_VolumeSlider, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_VolumeSlider, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_VolumeSlider, lv_color_hex(0x00FF08), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_VolumeSlider, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_VolumeSlider, 50, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_VolumeSlider, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_VolumeSlider, 12, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_VolumeSlider, lv_color_hex(0x00FF08), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_VolumeSlider, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_main_stop(ui_VolumeSlider, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_VolumeSlider, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_VolumeSlider, &ui_img_pot_ver_knob_png, LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_VolumeSlider, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_VolumeSlider, 100, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_VolumeSlider, 30, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_VolumeSlider, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_VolumeSlider, 5, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_VolumeSlider, 5, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_VolumeSlider, 3, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_VolumeSlider, 2, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_VolumeSlider, 6, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_VolumeSlider, 6, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_VolumeSlider, 12, LV_PART_KNOB| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_VolumeSlider, lv_color_hex(0x00FF08), LV_PART_KNOB | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_VolumeSlider, 255, LV_PART_KNOB| LV_STATE_PRESSED);
lv_obj_set_style_shadow_color(ui_VolumeSlider, lv_color_hex(0x00FF08), LV_PART_KNOB | LV_STATE_PRESSED );
lv_obj_set_style_shadow_opa(ui_VolumeSlider, 255, LV_PART_KNOB| LV_STATE_PRESSED);
lv_obj_set_style_shadow_width(ui_VolumeSlider, 40, LV_PART_KNOB| LV_STATE_PRESSED);
lv_obj_set_style_shadow_spread(ui_VolumeSlider, 0, LV_PART_KNOB| LV_STATE_PRESSED);
lv_obj_set_style_shadow_ofs_x(ui_VolumeSlider, 0, LV_PART_KNOB| LV_STATE_PRESSED);
lv_obj_set_style_shadow_ofs_y(ui_VolumeSlider, 0, LV_PART_KNOB| LV_STATE_PRESSED);

ui_LabelVolume = lv_label_create(ui_VolumePanel);
lv_obj_set_width( ui_LabelVolume, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelVolume, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelVolume, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_LabelVolume,"Volume");

ui_PanelGameSettings = lv_obj_create(ui_Settings);
lv_obj_set_width( ui_PanelGameSettings, 280);
lv_obj_set_height( ui_PanelGameSettings, 150);
lv_obj_set_x( ui_PanelGameSettings, 175 );
lv_obj_set_y( ui_PanelGameSettings, 40 );
lv_obj_clear_flag( ui_PanelGameSettings, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_PanelGameSettings, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelGameSettings, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelGameScoreReset = lv_label_create(ui_PanelGameSettings);
lv_obj_set_width( ui_LabelGameScoreReset, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelGameScoreReset, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelGameScoreReset, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_LabelGameScoreReset,"Game Score Reset");

ui_BrickScoreResetButton = lv_btn_create(ui_PanelGameSettings);
lv_obj_set_width( ui_BrickScoreResetButton, 80);
lv_obj_set_height( ui_BrickScoreResetButton, 40);
lv_obj_set_x( ui_BrickScoreResetButton, -20 );
lv_obj_set_y( ui_BrickScoreResetButton, 30 );
lv_obj_set_align( ui_BrickScoreResetButton, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_BrickScoreResetButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BrickScoreResetButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_BrickScoreResetButton, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_BrickScoreResetButton, lv_color_hex(0x9399A1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BrickScoreResetButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_BrickScoreResetButton, lv_color_hex(0x484B4F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_BrickScoreResetButton, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_BrickScoreResetButton, lv_color_hex(0x00FF08), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_shadow_opa(ui_BrickScoreResetButton, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_width(ui_BrickScoreResetButton, 5, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_spread(ui_BrickScoreResetButton, 5, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_ofs_x(ui_BrickScoreResetButton, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_ofs_y(ui_BrickScoreResetButton, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_color(ui_BrickScoreResetButton, lv_color_hex(0x00FF08), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_shadow_opa(ui_BrickScoreResetButton, 255, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_shadow_width(ui_BrickScoreResetButton, 5, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_shadow_spread(ui_BrickScoreResetButton, 5, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_shadow_ofs_x(ui_BrickScoreResetButton, 0, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_shadow_ofs_y(ui_BrickScoreResetButton, 0, LV_PART_MAIN| LV_STATE_FOCUSED);

ui_Label1 = lv_label_create(ui_BrickScoreResetButton);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"Reset");
lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label1, 200, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BrickBestScoreSettingsValue = lv_label_create(ui_PanelGameSettings);
lv_obj_set_width( ui_BrickBestScoreSettingsValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BrickBestScoreSettingsValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BrickBestScoreSettingsValue, 0 );
lv_obj_set_y( ui_BrickBestScoreSettingsValue, 40 );
lv_label_set_text(ui_BrickBestScoreSettingsValue,"Brick:");

ui_WolfBestScoreSettingsValue = lv_label_create(ui_PanelGameSettings);
lv_obj_set_width( ui_WolfBestScoreSettingsValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_WolfBestScoreSettingsValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_WolfBestScoreSettingsValue, 0 );
lv_obj_set_y( ui_WolfBestScoreSettingsValue, 90 );
lv_label_set_text(ui_WolfBestScoreSettingsValue,"Wolf:");

ui_BrickScoreResetButton1 = lv_btn_create(ui_PanelGameSettings);
lv_obj_set_width( ui_BrickScoreResetButton1, 80);
lv_obj_set_height( ui_BrickScoreResetButton1, 40);
lv_obj_set_x( ui_BrickScoreResetButton1, -20 );
lv_obj_set_y( ui_BrickScoreResetButton1, 80 );
lv_obj_set_align( ui_BrickScoreResetButton1, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_BrickScoreResetButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BrickScoreResetButton1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_BrickScoreResetButton1, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_BrickScoreResetButton1, lv_color_hex(0x9399A1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BrickScoreResetButton1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_BrickScoreResetButton1, lv_color_hex(0x484B4F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_BrickScoreResetButton1, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_BrickScoreResetButton1, lv_color_hex(0x00FF08), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_shadow_opa(ui_BrickScoreResetButton1, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_width(ui_BrickScoreResetButton1, 5, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_spread(ui_BrickScoreResetButton1, 5, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_ofs_x(ui_BrickScoreResetButton1, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_ofs_y(ui_BrickScoreResetButton1, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_color(ui_BrickScoreResetButton1, lv_color_hex(0x00FF08), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_shadow_opa(ui_BrickScoreResetButton1, 255, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_shadow_width(ui_BrickScoreResetButton1, 5, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_shadow_spread(ui_BrickScoreResetButton1, 5, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_shadow_ofs_x(ui_BrickScoreResetButton1, 0, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_shadow_ofs_y(ui_BrickScoreResetButton1, 0, LV_PART_MAIN| LV_STATE_FOCUSED);

ui_Label2 = lv_label_create(ui_BrickScoreResetButton1);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"Reset");
lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label2, 200, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BackSettingsButton = lv_btn_create(ui_Settings);
lv_obj_set_width( ui_BackSettingsButton, 50);
lv_obj_set_height( ui_BackSettingsButton, 25);
lv_obj_set_x( ui_BackSettingsButton, 10 );
lv_obj_set_y( ui_BackSettingsButton, 10 );
lv_obj_add_flag( ui_BackSettingsButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BackSettingsButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_BackSettingsButton, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_BackSettingsButton, lv_color_hex(0x9399A1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BackSettingsButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_BackSettingsButton, lv_color_hex(0x484B4F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_BackSettingsButton, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_BackSettingsButton, lv_color_hex(0x00FF08), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_shadow_opa(ui_BackSettingsButton, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_width(ui_BackSettingsButton, 5, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_spread(ui_BackSettingsButton, 5, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_ofs_x(ui_BackSettingsButton, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_ofs_y(ui_BackSettingsButton, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_shadow_color(ui_BackSettingsButton, lv_color_hex(0x00FF08), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_shadow_opa(ui_BackSettingsButton, 255, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_shadow_width(ui_BackSettingsButton, 5, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_shadow_spread(ui_BackSettingsButton, 5, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_shadow_ofs_x(ui_BackSettingsButton, 0, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_shadow_ofs_y(ui_BackSettingsButton, 0, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_shadow_color(ui_BackSettingsButton, lv_color_hex(0x00FF08), LV_PART_MAIN | LV_STATE_CHECKED|LV_STATE_PRESSED );
lv_obj_set_style_shadow_opa(ui_BackSettingsButton, 255, LV_PART_MAIN| LV_STATE_CHECKED|LV_STATE_PRESSED);
lv_obj_set_style_shadow_width(ui_BackSettingsButton, 5, LV_PART_MAIN| LV_STATE_CHECKED|LV_STATE_PRESSED);
lv_obj_set_style_shadow_spread(ui_BackSettingsButton, 5, LV_PART_MAIN| LV_STATE_CHECKED|LV_STATE_PRESSED);
lv_obj_set_style_shadow_ofs_x(ui_BackSettingsButton, 0, LV_PART_MAIN| LV_STATE_CHECKED|LV_STATE_PRESSED);
lv_obj_set_style_shadow_ofs_y(ui_BackSettingsButton, 0, LV_PART_MAIN| LV_STATE_CHECKED|LV_STATE_PRESSED);

ui_Label12 = lv_label_create(ui_BackSettingsButton);
lv_obj_set_width( ui_Label12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label12, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label12,"Back");
lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label12, 200, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelDeviceInfo = lv_obj_create(ui_Settings);
lv_obj_set_width( ui_PanelDeviceInfo, 280);
lv_obj_set_height( ui_PanelDeviceInfo, 100);
lv_obj_set_x( ui_PanelDeviceInfo, 175 );
lv_obj_set_y( ui_PanelDeviceInfo, 200 );
lv_obj_clear_flag( ui_PanelDeviceInfo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_PanelDeviceInfo, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelDeviceInfo, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelDeviceInfo = lv_label_create(ui_PanelDeviceInfo);
lv_obj_set_width( ui_LabelDeviceInfo, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelDeviceInfo, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelDeviceInfo, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_LabelDeviceInfo,"Connected device:");
lv_obj_set_style_text_color(ui_LabelDeviceInfo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelDeviceInfo, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_BrickScoreResetButton, ui_event_BrickScoreResetButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BrickScoreResetButton1, ui_event_BrickScoreResetButton1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BackSettingsButton, ui_event_BackSettingsButton, LV_EVENT_ALL, NULL);

}
